export const serbiaStates = [
    "Central Serbia",
    "Kosovo and Metohija",
    "Vojvodina"
];

export const serbiaCities = {
    "Central Serbia": [
        "Belgrade",
        "Niš",
        "Kragujevac",
        "Čačak",
        "Novi Pazar",
        "Kraljevo",
        "Jagodina",
        "Šabac",
        "Smederevo",
        "Leskovac",
        "Valjevo",
        "Kruševac",
        "Užice",
        "Vranje",
        "Zaječar"
    ],
    "Kosovo and Metohija": [
        "Priština",
        "Prizren",
        "Peć",
        "Kosovska Mitrovica",
        "Gnjilane",
        "Uroševac",
        "Đakovica",
        "Orahovac"
    ],
    "Vojvodina": [
        "Novi Sad",
        "Subotica",
        "Zrenjanin",
        "Pančevo",
        "Sombor",
        "Kikinda",
        "Sremska Mitrovica",
        "Vršac",
        "Ruma",
        "Bačka Palanka",
        "Inđija",
        "Bečej",
        "Senta",
        "Apatin",
        "Temerin"
    ]
};
// Switzerland Cantons (states)
export const switzerlandStates = [
    "Aargau",
    "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Bern",
    "Fribourg",
    "Geneva",
    "Glarus",
    "Graubünden",
    "Jura",
    "Lucerne",
    "Neuchâtel",
    "Nidwalden",
    "Obwalden",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "St. Gallen",
    "Thurgau",
    "Ticino",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zurich"
];

// Switzerland Cities by Canton
export const switzerlandCities = {
    "Aargau": [
        "Aarau",
        "Baden",
        "Brugg",
        "Rheinfelden",
        "Lenzburg",
        "Wettingen",
        "Spreitenbach",
        "Zofingen",
        "Oftringen",
        "Wohlen",
        "Muri",
        "Suhr",
        "Untersiggenthal"
    ],
    "Appenzell Ausserrhoden": [
        "Herisau",
        "Heiden",
        "Trogen",
        "Teufen",
        "Gais",
        "Speicher",
        "Schwellbrunn"
    ],
    "Appenzell Innerrhoden": [
        "Appenzell",
        "Gonten",
        "Oberegg",
        "Schlatt-Haslen",
        "Schwende"
    ],
    "Basel-Landschaft": [
        "Liestal",
        "Pratteln",
        "Muttenz",
        "Allschwil",
        "Binningen",
        "Reinach",
        "Birsfelden",
        "Münchenstein",
        "Aesch",
        "Arlesheim",
        "Sissach",
        "Laufen"
    ],
    "Basel-Stadt": [
        "Basel",
        "Bettingen",
        "Riehen"
    ],
    "Bern": [
        "Bern",
        "Biel/Bienne",
        "Thun",
        "Köniz",
        "Langenthal",
        "Burgdorf",
        "Spiez",
        "Steffisburg",
        "Ostermundigen",
        "Muri bei Bern",
        "Belp",
        "Worb",
        "Münsingen",
        "Interlaken",
        "Langnau im Emmental"
    ],
    "Fribourg": [
        "Fribourg",
        "Bulle",
        "Villars-sur-Glâne",
        "Düdingen",
        "Murten",
        "Estavayer-le-Lac",
        "Romont",
        "Tafers",
        "Schwarzsee",
        "Châtel-Saint-Denis"
    ],
    "Geneva": [
        "Geneva",
        "Vernier",
        "Lancy",
        "Meyrin",
        "Carouge",
        "Onex",
        "Thônex",
        "Versoix",
        "Le Grand-Saconnex",
        "Chêne-Bougeries",
        "Plan-les-Ouates",
        "Bernex"
    ],
    "Glarus": [
        "Glarus",
        "Näfels",
        "Mollis",
        "Netstal"
    ],
    "Graubünden": [
        "Chur",
        "Davos",
        "St. Moritz",
        "Thusis",
        "Ilanz",
        "Klosters-Serneus",
        "Arosa",
        "Scuol",
        "Flims",
        "Laax"
    ],
    "Jura": [
        "Delémont",
        "Porrentruy",
        "Saignelégier",
        "Courroux",
        "Courfaivre"
    ],
    "Lucerne": [
        "Lucerne",
        "Emmen",
        "Kriens",
        "Horw",
        "Ebikon",
        "Sursee",
        "Weggis",
        "Hochdorf",
        "Willisau",
        "Ruswil"
    ],
    "Neuchâtel": [
        "Neuchâtel",
        "La Chaux-de-Fonds",
        "Le Locle",
        "Val-de-Ruz",
        "Boudry",
        "Corcelles-Cormondrèche",
        "Peseux"
    ],
    "Nidwalden": [
        "Stans",
        "Buochs",
        "Hergiswil",
        "Beckenried",
        "Ennetbürgen",
        "Oberdorf"
    ],
    "Obwalden": [
        "Sarnen",
        "Alpnach",
        "Kerns",
        "Giswil",
        "Sachseln"
    ],
    "Schaffhausen": [
        "Schaffhausen",
        "Neuhausen am Rheinfall",
        "Beringen",
        "Thayngen",
        "Stein am Rhein"
    ],
    "Schwyz": [
        "Schwyz",
        "Arth",
        "Ingenbohl",
        "Küssnacht",
        "Lachen",
        "Wollerau",
        "Freienbach",
        "Brunnen"
    ],
    "Solothurn": [
        "Solothurn",
        "Olten",
        "Grenchen",
        "Zuchwil",
        "Dornach",
        "Biberist",
        "Derendingen",
        "Balsthal"
    ],
    "St. Gallen": [
        "St. Gallen",
        "Rapperswil-Jona",
        "Wil",
        "Gossau",
        "Uzwil",
        "Flawil",
        "Wattwil",
        "Buchs",
        "Altstätten",
        "Bad Ragaz",
        "Sargans"
    ],
    "Thurgau": [
        "Frauenfeld",
        "Kreuzlingen",
        "Arbon",
        "Amriswil",
        "Weinfelden",
        "Romanshorn",
        "Sirnach",
        "Diessenhofen",
        "Bischofszell"
    ],
    "Ticino": [
        "Lugano",
        "Bellinzona",
        "Locarno",
        "Mendrisio",
        "Chiasso",
        "Giubiasco",
        "Biasca",
        "Ascona",
        "Minusio",
        "Cadempino"
    ],
    "Uri": [
        "Altdorf",
        "Andermatt",
        "Erstfeld",
        "Bürglen",
        "Schattdorf"
    ],
    "Valais": [
        "Sion",
        "Martigny",
        "Brig-Glis",
        "Monthey",
        "Visp",
        "Sierre",
        "Saas-Fee",
        "Zermatt",
        "Crans-Montana",
        "Verbier",
        "Leukerbad",
        "Lötschental"
    ],
    "Vaud": [
        "Lausanne",
        "Yverdon-les-Bains",
        "Montreux",
        "Nyon",
        "Vevey",
        "Renens",
        "Pully",
        "Morges",
        "Prilly",
        "Aigle",
        "Rolle",
        "Gland",
        "Château-d'Oex"
    ],
    "Zug": [
        "Zug",
        "Baar",
        "Cham",
        "Steinhausen",
        "Rotkreuz",
        "Unterägeri"
    ],
    "Zurich": [
        "Zurich",
        "Winterthur",
        "Uster",
        "Dübendorf",
        "Dietikon",
        "Wetzikon",
        "Schlieren",
        "Kloten",
        "Bülach",
        "Volketswil",
        "Opfikon",
        "Wallisellen",
        "Adliswil",
        "Regensdorf",
        "Thalwil",
        "Horgen"
    ]
};

export const customStates = {
    ZA: [
        "Eastern Cape",
        "Free State",
        "Gauteng",
        "KwaZulu-Natal",
        "Limpopo",
        "Mpumalanga",
        "Northern Cape",
        "North West",
        "Western Cape",
    ],
    AU: [
        "Australian Capital Territory",
        "New South Wales",
        "Northern Territory",
        "Queensland",
        "South Australia",
        "Tasmania",
        "Victoria",
        "Western Australia"
    ],
     CH: switzerlandStates 
};

// Add Czech Republic states
export const czechStates = [
    "Prague",
    "Central Bohemian",
    "South Bohemian",
    "Plzeň",
    "Karlovy Vary",
    "Ústí nad Labem",
    "Liberec",
    "Hradec Králové",
    "Pardubice",
    "Vysočina",
    "South Moravian",
    "Olomouc",
    "Moravian-Silesian",
    "Zlín"
];

// Add Czech Republic cities
export const czechCities = {
    "Prague": [
        "Prague 1",
        "Prague 2",
        "Prague 3",
        "Prague 4",
        "Prague 5",
        "Prague 6",
        "Prague 7",
        "Prague 8",
        "Prague 9",
        "Prague 10"
    ],
    "Central Bohemian": [
        "Kladno",
        "Mladá Boleslav",
        "Příbram",
        "Kolín",
        "Kutná Hora",
        "Mělník",
        "Beroun",
        "Nymburk",
        "Benátky nad Jizerou",
        "Poděbrady",
        "Rakovník",
        "Slaný",
        "Benešov",
        "Čáslav",
        "Lysá nad Labem"
    ],
    "South Bohemian": [
        "České Budějovice",
        "Tábor",
        "Písek",
        "Strakonice",
        "Jindřichův Hradec",
        "Český Krumlov",
        "Prachatice",
        "Milevsko",
        "Třeboň",
        "Vimperk",
        "Kaplice",
        "Soběslav",
        "Blatná",
        "Vodňany",
        "Dačice"
    ],
    "Plzeň": [
        "Plzeň",
        "Klatovy",
        "Rokycany",
        "Sušice",
        "Domažlice",
        "Tachov",
        "Stříbro",
        "Nýřany",
        "Přeštice",
        "Horažďovice",
        "Kralovice",
        "Blovice"
    ],
    "Karlovy Vary": [
        "Karlovy Vary",
        "Cheb",
        "Sokolov",
        "Mariánské Lázně",
        "Františkovy Lázně",
        "Ostrov",
        "Chodov",
        "Aš",
        "Horní Slavkov",
        "Nejdek"
    ],
    "Ústí nad Labem": [
        "Ústí nad Labem",
        "Most",
        "Teplice",
        "Děčín",
        "Chomutov",
        "Litoměřice",
        "Louny",
        "Kadaň",
        "Žatec",
        "Roudnice nad Labem",
        "Bílina",
        "Krupka",
        "Varnsdorf",
        "Rumburk",
        "Štětí"
    ],
    "Liberec": [
        "Liberec",
        "Jablonec nad Nisou",
        "Česká Lípa",
        "Semily",
        "Turnov",
        "Tanvald",
        "Frýdlant",
        "Lomnice nad Popelkou",
        "Hrádek nad Nisou"
    ],
    "Hradec Králové": [
        "Hradec Králové",
        "Jičín",
        "Náchod",
        "Trutnov",
        "Rychnov nad Kněžnou",
        "Dvůr Králové nad Labem",
        "Hořice",
        "Nová Paka",
        "Kostelec nad Orlicí",
        "Broumov",
        "Nové Město nad Metují"
    ],
    "Pardubice": [
        "Pardubice",
        "Chrudim",
        "Svitavy",
        "Ústí nad Orlicí",
        "Česká Třebová",
        "Vysoké Mýto",
        "Litomyšl",
        "Moravská Třebová",
        "Lanškroun",
        "Polička"
    ],
    "Vysočina": [
        "Jihlava",
        "Třebíč",
        "Žďár nad Sázavou",
        "Pelhřimov",
        "Havlíčkův Brod",
        "Velké Meziříčí",
        "Moravské Budějovice",
        "Chotěboř",
        "Brtnice",
        "Náměšť nad Oslavou"
    ],
    "South Moravian": [
        "Brno",
        "Znojmo",
        "Blansko",
        "Hodonín",
        "Břeclav",
        "Vyškov",
        "Kyjov",
        "Kuřim",
        "Boskovice",
        "Mikulov",
        "Tišnov",
        "Pohořelice",
        "Ivančice",
        "Slavkov u Brna",
        "Šlapanice"
    ],
    "Olomouc": [
        "Olomouc",
        "Prostějov",
        "Přerov",
        "Šumperk",
        "Jeseník",
        "Litovel",
        "Mohelnice",
        "Uničov",
        "Lipník nad Bečvou",
        "Hranice",
        "Zábřeh",
        "Šternberk"
    ],
    "Moravian-Silesian": [
        "Ostrava",
        "Havířov",
        "Karviná",
        "Frýdek-Místek",
        "Opava",
        "Třinec",
        "Orlová",
        "Nový Jičín",
        "Český Těšín",
        "Krnov",
        "Bruntál",
        "Kopřivnice",
        "Bohumín",
        "Vítkov",
        "Frenštát pod Radhoštěm"
    ],
    "Zlín": [
        "Zlín",
        "Kroměříž",
        "Vsetín",
        "Uherské Hradiště",
        "Valašské Meziříčí",
        "Rožnov pod Radhoštěm",
        "Otrokovice",
        "Holešov",
        "Napajedla",
        "Bystřice pod Hostýnem",
        "Luhačovice",
        "Slavičín"
    ]
};


export const customCities = {
    ZA: {
        "Eastern Cape": [
            "East London",
            "Port Elizabeth",
            "Mthatha",
            "Queenstown",
            "Bhisho",
            "King William's Town",
            "Grahamstown",
            "Port Alfred",
            "Jeffreys Bay",
            "Cradock",
            "Butterworth",
            "Aliwal North",
            "Fort Beaufort",
            "Uitenhage",
            "Komani"
        ],
        "Free State": [
            "Bloemfontein",
            "Welkom",
            "Bethlehem",
            "Phuthaditjhaba",
            "Sasolburg",
            "Kroonstad",
            "Botshabelo",
            "Parys",
            "Virginia",
            "Odendaalsrus",
            "Harrismith",
            "Ladybrand",
            "Ficksburg",
            "Marquard",
            "Heilbron"
        ],
        "Gauteng": [
            "Johannesburg",
            "Pretoria",
            "Soweto",
            "Midrand",
            "Sandton",
            "Centurion",
            "Randburg",
            "Roodepoort",
            "Boksburg",
            "Benoni",
            "Germiston",
            "Alberton",
            "Krugersdorp",
            "Vanderbijlpark",
            "Vereeniging",
            "Springs",
            "Edenvale",
            "Kempton Park",
            "Tembisa",
            "Alexandra"
        ],
        "KwaZulu-Natal": [
            "Durban",
            "Pietermaritzburg",
            "Richards Bay",
            "Newcastle",
            "Pinetown",
            "Umlazi",
            "Tongaat",
            "Empangeni",
            "Ladysmith",
            "Ulundi",
            "Port Shepstone",
            "Stanger",
            "Amanzimtoti",
            "Mtubatuba",
            "Scottburgh",
            "Eshowe",
            "Vryheid",
            "Kokstad",
            "Hluhluwe",
            "Margate"
        ],
        "Limpopo": [
            "Polokwane",
            "Tzaneen",
            "Thohoyandou",
            "Mokopane",
            "Lephalale",
            "Bela-Bela",
            "Phalaborwa",
            "Giyani",
            "Louis Trichardt",
            "Musina",
            "Burgersfort",
            "Lebowakgomo",
            "Modimolle",
            "Thabazimbi",
            "Nylstroom"
        ],
        "Mpumalanga": [
            "Nelspruit",
            "Witbank",
            "Middelburg",
            "Secunda",
            "Standerton",
            "Ermelo",
            "Barberton",
            "Lydenburg",
            "Hazyview",
            "White River",
            "Piet Retief",
            "Hendrina",
            "Bethal",
            "Graskop",
            "Komatipoort"
        ],
        "Northern Cape": [
            "Kimberley",
            "Upington",
            "Springbok",
            "De Aar",
            "Kuruman",
            "Douglas",
            "Postmasburg",
            "Prieska",
            "Calvinia",
            "Carnarvon",
            "Colesberg",
            "Britstown",
            "Vredendal",
            "Loxton",
            "Keimoes"
        ],
        "North West": [
            "Rustenburg",
            "Mahikeng",
            "Klerksdorp",
            "Potchefstroom",
            "Brits",
            "Lichtenburg",
            "Vryburg",
            "Zeerust",
            "Orkney",
            "Stilfontein",
            "Christiana",
            "Wolmaransstad",
            "Delareyville",
            "Swartruggens",
            "Koster"
        ],
        "Western Cape": [
            "Cape Town",
            "Stellenbosch",
            "Paarl",
            "George",
            "Worcester",
            "Hermanus",
            "Mossel Bay",
            "Somerset West",
            "Knysna",
            "Oudtshoorn",
            "Bellville",
            "Strand",
            "Brackenfell",
            "Mitchells Plain",
            "Claremont",
            "Plettenberg Bay",
            "Swellendam",
            "Robertson",
            "Malmesbury",
            "Vredenburg"
        ],
    },
    AU: {
        "Australian Capital Territory": [
            "Canberra",
            "Belconnen",
            "Gungahlin",
            "Tuggeranong",
            "Weston Creek",
            "Woden Valley"
        ],
        "New South Wales": [
            "Sydney",
            "Newcastle",
            "Wollongong",
            "Central Coast",
            "Parramatta",
            "Penrith",
            "Campbelltown",
            "Blacktown",
            "Liverpool",
            "Coffs Harbour",
            "Wagga Wagga",
            "Albury",
            "Tamworth",
            "Port Macquarie",
            "Orange",
            "Dubbo",
            "Bathurst",
            "Lismore",
            "Nowra",
            "Gosford"
        ],
        "Northern Territory": [
            "Darwin",
            "Alice Springs",
            "Palmerston",
            "Katherine",
            "Nhulunbuy",
            "Tennant Creek",
            "Yulara",
            "Kakadu",
            "Jabiru"
        ],
        "Queensland": [
            "Brisbane",
            "Gold Coast",
            "Sunshine Coast",
            "Townsville",
            "Cairns",
            "Toowoomba",
            "Mackay",
            "Rockhampton",
            "Bundaberg",
            "Hervey Bay",
            "Gladstone",
            "Mount Isa",
            "Ipswich",
            "Logan City",
            "Redland City",
            "Caloundra",
            "Maroochydore",
            "Noosa",
            "Gympie"
        ],
        "South Australia": [
            "Adelaide",
            "Mount Gambier",
            "Whyalla",
            "Murray Bridge",
            "Port Lincoln",
            "Port Augusta",
            "Gawler",
            "Victor Harbor",
            "Renmark",
            "Berri",
            "Naracoorte",
            "Port Pirie"
        ],
        "Tasmania": [
            "Hobart",
            "Launceston",
            "Devonport",
            "Burnie",
            "Ulverstone",
            "Kingston",
            "Sandy Bay",
            "New Norfolk",
            "Smithton",
            "St Helens"
        ],
        "Victoria": [
            "Melbourne",
            "Geelong",
            "Ballarat",
            "Bendigo",
            "Shepparton",
            "Melton",
            "Sunbury",
            "Werribee",
            "Frankston",
            "Pakenham",
            "Traralgon",
            "Warrnambool",
            "Wangaratta",
            "Mildura",
            "Horsham",
            "Sale",
            "Moe",
            "Morwell",
            "Dandenong",
            "Cranbourne"
        ],
        "Western Australia": [
            "Perth",
            "Bunbury",
            "Geraldton",
            "Albany",
            "Mandurah",
            "Kalgoorlie",
            "Port Hedland",
            "Karratha",
            "Broome",
            "Rockingham",
            "Fremantle",
            "Joondalup",
            "Midland",
            "Busselton",
            "Esperance",
            "Margaret River",
            "Newman",
            "Carnarvon",
            "Northam",
            "Kununurra"
        ]
    },
     CZ: czechCities,
     CH: switzerlandCities
};